Allow users to manage archival status of owned pits
DuckBot-Discord/duck-hideout-manager-bot pull request #11
Opened 2023-04-16 04:13 UTC by cyrus01337

Solves #10

2023-04-19 12:01 UTC, cyrus01337 commented
There were plans to include automatic archival, which will carry over in a separate issue and corresponding PR.

2023-04-19 17:55 UTC, LeoCx1000 requested changes
A few things I've noticed.

2023-04-19 17:55 UTC, LeoCx1000 commented on cogs/hideout/pits.py
> +        archive_mode = ArchiveMode(record['archive_mode'])
PostgreSQL enums return [strings](https://github.com/DuckBot-Discord/duck-hideout-manager-bot/blob/main/cogs/hideout/pits.py#L487) not integers, either check literals directly or update the enum values to be strings.

2023-04-19 17:55 UTC, LeoCx1000 commented on cogs/hideout/pits.py
> +            raise ActionNotExecutable('This pit was marked as inactive, only the counsellors can unarchive it.')
This logic should be the other way around, manual (archived by a counsellor) should not permit users from unarchiving it. Users should only be able to unarchive their own pit if it's been archived automatically.

```suggestion
        if archive_mode is ArchiveMode.INACTIVE and ctx.author != owner or is_not_counselor:
            raise ActionNotExecutable('This pit was marked as inactive, only the pit owner and counsellors can unarchive it.')
        elif archive_mode is ArchiveMode.MANUAL and is_not_counselor:
            raise ActionNotExecutable('This pit was manually archived, only the counsellors can unarchive it.')
```

2023-04-20 09:50 UTC, cyrus01337 commented on cogs/hideout/pits.py
> +        archive_mode = ArchiveMode(record['archive_mode'])
I have not dabbled with enums as much as I had liked, so this flew completely over me!

2023-04-20 09:51 UTC, cyrus01337 commented on cogs/hideout/pits.py
> +            raise ActionNotExecutable('This pit was marked as inactive, only the counsellors can unarchive it.')
Swapped!

2023-04-20 09:52 UTC, cyrus01337 reviewed
Resolved.

2023-04-20 09:57 UTC, LeoCx1000 approved these changes

2023-04-20 09:57 UTC, merged