Add commands for managing boosting roles
DuckBot-Discord/duck-hideout-manager-bot pull request #19
Opened 2023-10-16 15:32 UTC by itswilliboy

2023-10-16 15:51 UTC, LeoCx1000 requested changes
Some minor issues I noticed...

2023-10-16 15:51 UTC, LeoCx1000 commented on cogs/hideout/boost_roles.py
> +    role = RoleGroup(name="role", description="Commands for manging your boost role.", parent=boost)
boost = app_commands.Group(name="boost", description="Commands for managing your boost.", guild_only=True)
    @app_commands.guild_only()
    role = app_commands.Group(name="role", description="Commands for manging your boost role.", parent=boost)

2023-10-16 15:51 UTC, LeoCx1000 commented on cogs/hideout/boost_roles.py
> +BOOSTER_ROLE_ID: int = 878410045505798154
Should use ``guild.premium_subscriber_role`` instead of hard-coding it

2023-10-16 15:51 UTC, LeoCx1000 commented on cogs/hideout/boost_roles.py
> +        """
```suggestion
        text = (
            f"Successfully edited {role.mention}"
            f"\nName: {role}"
            f"\nColor: {db['role_colour'].upper()}"
        )
```
Doing it this way prevents unwanted indentation showing up on discord

2023-10-16 15:51 UTC, crygup commented
`BOOSTER_ROLE_ID` is only used once in the same file and redundant, use [premium_subscriber_role](https://discordpy.readthedocs.io/en/stable/api.html?#discord.Guild.premium_subscriber_role)

2023-10-28 12:12 UTC, LeoCx1000 requested changes
Seems mostly good. Some things I have noticed are the following
- roles are crated at the bottom, and will need to be moved to role ``1079187727695740960``'s position + 1.
- the current database schema and code doesn't seem to account for when an emoji is a default emoji. Trying to read a default emoji [will ValueError](https://github.com/Rapptz/discord.py/blob/master/discord/partial_emoji.py#L267).
Other than that, everything seems fine.

2023-10-28 12:30 UTC, NightSlasher35 reviewed
LGTM, I don't see any more issues other than what leo said.

2023-10-28 21:24 UTC, LeoCx1000 requested changes

2023-10-28 21:24 UTC, LeoCx1000 commented on cogs/hideout/boost_roles.py
> +            )
There is potential data loss here as [role.icon is None when it is a unicode emoji](https://discordpy.readthedocs.io/en/stable/api.html#discord.Role.icon). The best way to handle this would be to add another database column for [role.unicode_emoji](https://discordpy.readthedocs.io/en/stable/api.html#discord.Role.unicode_emoji) then handle that as-well in `member_update` when creating the role.

2023-10-28 21:24 UTC, LeoCx1000 commented on cogs/hideout/boost_roles.py
> +        )
Same here.

2023-11-02 21:59 UTC, itswilliboy commented on cogs/hideout/boost_roles.py
> +            )
Will fix soon when I have time. ^^

2024-03-31 01:22 UTC, LeoCx1000 requested changes, later dismissed
Overall seems fine but a few things that need changes:

2024-03-31 01:22 UTC, LeoCx1000 commented on cogs/hideout/boost_roles.py
> +        return await partial.read()
Due to the nature of the `is_unicode_emoji` check - as seen [here](https://github.com/Rapptz/discord.py/blob/v2.3.x/discord/partial_emoji.py#L213-L215), this function is best to be rewritten as following. If not checked this way, this could allow any arbitrary string to be passed due to the nature of the aforementioned method

```suggestion
    async def get_emoji(input: str) -> Optional[Union[str, bytes]]:
        partial = discord.PartialEmoji.from_str(input)
        
        if partial.is_unicode_emoji():
            if is_emoji(partial.name):
                return partial.name

        else:
            return await partial.read()
```

2024-03-31 01:22 UTC, LeoCx1000 commented on cogs/hideout/boost_roles.py
> +            except (discord.HTTPException, discord.Forbidden) as exc:
Forbidden is a subclass of HTTPException
```suggestion
            except discord.HTTPException as exc:
```

2024-03-31 01:22 UTC, LeoCx1000 commented on cogs/hideout/boost_roles.py
> +    async def create(
Due to the amount of API calls, I would prefer a early-defer + followup flow in this method, to allow rate limits to cause "interaction not responded" errors.

2024-03-31 01:22 UTC, LeoCx1000 commented on cogs/hideout/boost_roles.py
> +            icon: Optional[bytes] = db["role_icon"]
```suggestion
            icon: Optional[Union[bytes, str]] = db["role_icon"] or db["unicode_emoji"]
```

2024-03-31 01:22 UTC, LeoCx1000 commented on cogs/hideout/boost_roles.py
> +        icon_: Optional[Union[str, discord.PartialEmoji, bytes]]
```suggestion
        icon_: Optional[Union[str, bytes]]
```

2024-03-31 01:22 UTC, LeoCx1000 commented on cogs/hideout/boost_roles.py
> +            await interaction.response.send_message("Something went wrong when trying to create the role.", ephemeral=True)
```suggestion
        except discord.HTTPException as e:
            await interaction.response.send_message(f"Something went wrong when trying to create the role:\n{e}", ephemeral=True)
```

2024-03-31 01:22 UTC, LeoCx1000 commented on cogs/hideout/boost_roles.py
> +    async def edit(
Same here, early (ephemeral) defer + followups.

2024-03-31 01:22 UTC, LeoCx1000 commented on cogs/hideout/boost_roles.py
> +        if icon_ is not None:
why not `icon=icon_ or MISSING` like the rest?

2024-03-31 01:22 UTC, LeoCx1000 commented on cogs/hideout/boost_roles.py
> +        )
Don't forget to update the unicode_emoji too

```suggestion
        query = """
            UPDATE booster_roles
                SET role_name = $1,
                    role_colour = $2,
                    role_icon = $3,
                    unicode_emoji = $4
                WHERE role_id = $5
            RETURNING *
        """

        db = await interaction.client.pool.fetchrow(
            query, role.name, str(role.colour), role.icon and await role.icon.read(), role.unicode_emoji, role.id
        )
```

2024-03-31 01:22 UTC, LeoCx1000 commented on cogs/hideout/boost_roles.py
> +        await role.delete(reason=f"Nitro Boost Expired: {interaction.user}")
```suggestion
        await role.delete(reason=f"Manually deleted by: {interaction.user}")
```

2024-03-31 01:22 UTC, LeoCx1000 commented on cogs/hideout/boost_roles.py
> +        await interaction.response.send_message("Successfully deleted your boost role.")
add an `on_guild_role_delete` handler for if someone manually deletes one of these too. A simple blind DELETE is fine, without checking stuff or anything.

2024-03-31 02:12 UTC, Hadock-is-ok approved these changes
lgtm

2025-02-06 21:45 UTC, AbstractUmbra approved these changes

2025-02-06 21:45 UTC, merged