Add `AsyncInstance` class
DuckBot-Discord/duck-hideout-manager-bot pull request #9
Opened 2023-03-24 18:42 UTC by irregularunit

# About
As of [async_init](https://github.com/irregularunit/duck-hideout-manager-bot/blob/main/cogs/stats/calendar.py#L41) you have defined as an async coroutine with patching it with `async_init`.

This PR introduces a new `AsyncInstance` class that you can use to create async classes. This removes the need for you to patch the `__init__` method yourself, and hopefully making your code more readable and easier to maintain.

# Note
The current implementation needs better typings. I'm aware that the current implementation of the class does not strict type checking.

I find it too much of a hassle to fix the typing myself. That is why I cannot fix the annotations.

2023-03-24 19:03 UTC, LeoCx1000 requested changes
Hello. Thanks for your PR!

I would like to note a few things, first and foremost you cannot name a file `async`, since that keyword is reserved for defining async functions in python and it will fail to import.

Second, what would be the use of this class. That is, how should it be used? Adding a doc-string to `AsyncInstance` would be preferred so other contributors know how to use said class without having to read the code within it.

2023-03-24 19:56 UTC, irregularunit commented
Hi there,

I've made some changes to this code:

> I would like to note a few things, first and foremost you cannot name a file `async`, since that keyword is reserved for defining async functions in python and it will fail to import.

- Sorry for the rookie mistake.

> Second, what would be the use of this class. That is, how should it be used? Adding a doc-string to `AsyncInstance` would be preferred so other contributors know how to use said class without having to read the code within it.

- Added a class-level docstring to provide clarity on how to use the class which hopefully clears any questions on how to use this class.

Sorry for the rookie mistake in the initial commit. Let me know if there are any further changes you'd like me to make.

Thanks.

2023-03-24 22:42 UTC, LeoCx1000 commented
Thanks for the clarification. After trying out your example, pyright does not recognise this class is awaitable.

Unless this is addressed, I can't push this PR forwards, I would rather not have to litter the code with `type: ignore` comments that can be avoided.

![Code_KZh3W6bdOY](https://user-images.githubusercontent.com/13399568/227628933-18a95bf2-086a-4abf-a033-68ddaa5a1ca6.png)

2023-03-25 00:15 UTC, irregularunit commented
Hi there,

could you please review my pr again.

2023-03-25 10:56 UTC, LeoCx1000 requested changes
Thanks for addressing these changes. 

Another problem that I have encountered is that the linter does not recognise the arguments that are given to ``__ainit__`` so the intellisense for the constructor is missing, though I don't think that can be addressed.

Other than that, it all seems to work as expected.

2023-03-25 10:56 UTC, LeoCx1000 commented on utils/async_utils.py
> +from typing import Any, Callable, Coroutine, Generator, MutableSet, Optional, overload
```suggestion
from typing import Any, Callable, Coroutine, Generator, MutableSet, Optional, overload, Self
```

2023-03-25 10:56 UTC, LeoCx1000 commented on utils/async_utils.py
> +    def __await__(self) -> Generator[Any, None, AsyncInstance]:
```suggestion
    def __await__(self) -> Generator[Any, None, Self]:
```

Return ``typing.Self`` here so the linter knows which subclass it is when awaiting it.

```py
test = await Test()
reveal_type(test)  # type is AsyncInstance -> type is Test
```

2023-03-25 11:51 UTC, irregularunit commented
Good morning,

thanks for the improvements and suggestions, is there anything else you would like me to change?

2023-03-25 13:59 UTC, LeoCx1000 approved these changes
Seems fine.

2023-03-25 21:40 UTC, merged

2023-03-25 21:40 UTC, LeoCx1000 commented
Thanks